### ISSUE TITLE
Deploy as aar

### ISSUE THREAD

**Issue by dmitry-zaitsev** [hanspeide/anytextview#8]
In current state library is hardly usable with Gradle based projects (which is a majority of new projects at the time) as Gradle does not support apklib dependencies.

Could you instead deploy it as aar, so both Maven and Gradle users will be happy?

**Comment by hanspeide** [comment]
Project has been converted to use Gradle for building, and .aar for packaging. A new release has been deployed to Central. To use the new version, add the following in your build.gradle:
```javascript
dependencies {
    compile 'com.ctrlplusz.anytextview:library:1.2'
}
```

**Comment by dmitry-zaitsev** [comment]
:+1:

**Comment by hanspeide** [comment]
@dmitry-zaitsev Could you check that the library works for you?
